/// Display labels for prayer segment IDs (lookup data, not UI).
///
/// Returns the Hebrew label for a segment ID. An empty string means "no
/// label" (the segment is body text, not a section header). Unknown IDs fall
/// back to the raw ID so they remain visible in dev builds.
String segmentLabel(String id) {
  final label = _segmentLabels[id];
  if (label != null) return label;
  // Generated selichot segments (shared cross-day + day-specific piyutim) are
  // body text composed by the fast-day templates; they carry no section header.
  if (id.startsWith('selichot_')) return '';
  return id;
}

const _segmentLabels = <String, String>{
  // ── Lifnei HaTfila — morning prep ─────────────────────────────────────────
  'modeh_ani': 'מודה אני',
  'al_netilat_yadayim': 'על נטילת ידים',
  'asher_yatzar': 'אשר יצר',
  'elokai_neshama': 'אלקי נשמה',
  'birchot_hatorah_la_asok': 'ברכות התורה',
  'birchot_hatorah_vehaarev': '',
  'birchot_hatorah_natan_torah': '',
  'birchot_hatorah_pesukim': '',
  'vehaarev': '',
  'natan_torah': '',
  'pesukim': '',
  'elu_devarim': '',
  'yehi_ratzon_tzitzit': '',
  'birkat_tzitzit_gadol': 'ברכת ציצית',
  'mah_yakar_tallit': '',
  'birkat_tzitzit_katan': 'ברכת ציצית',
  'seder_tefillin': 'סדר הנחת תפילין',
  'parshat_kadesh': 'פרשת קדש לי',
  'parshat_vehaya_ki_yeviacha': 'פרשת והיה כי יביאך',
  'ma_tovu': 'מה טובו',
  'adon_olam': 'אדון עולם',
  'yigdal': 'יגדל',
  'vatitpalel_channa': '',
  'lshem_yichud': 'לשם יחוד',
  'lshem_yichud_maariv': 'לשם יחוד',
  'lshem_yichud_mincha': 'לשם יחוד',
  'mah_yedidot': 'מה יְּדִידוֹת',
  // ── Birkot HaShachar ──────────────────────────────────────────────────────
  'birkot_hashachar_header': 'ברכות השחר',
  'hanoten_lasechvi': '',
  'shelo_asani_goy': '',
  'shelo_asani_eved': '',
  'shelo_asani_ishah': '',
  'sheasani_kirtzono': '',
  'pokeach_ivrim': '',
  'malbish_arumim': '',
  'matir_asurim': '',
  'zokef_kefufim': '',
  'rokea_haaretz': '',
  'sheasah_li_kol_tzorki': '',
  'hamechin_mitzedei_gever': '',
  'ozer_yisrael': '',
  'oter_yisrael': '',
  'hanoten_layaef_koach': '',
  'hamaavir_sheinah': '',
  'yehi_ratzon_shelo_yavo': '',
  // ── Akeidah + intro to Korbanot ───────────────────────────────────────────
  'akeidah': 'פרשת העקידה',
  'akeidah_yehi_ratzon': '',
  'leolam_yehe_adam': 'לעולם יהא אדם',
  // ── Korbanot (whole segment + future sub-segments) ────────────────────────
  'korbanot': 'קרבנות',
  'korbanot_tamid': 'פרשת התמיד',
  'korbanot_ketoret_header': 'פרשת הקטורת',
  'korbanot_ketoret': '',
  'korbanot_pitum_header': 'פטום הקטורת',
  'korbanot_pitum': '',
  'korbanot_eizehu_header': 'פרק איזהו מקומן',
  'korbanot_eizehu': '',
  'korbanot_conclusion': 'ברייתא דרבי ישמעאל',
  // ── Pesukei DeZimra ───────────────────────────────────────────────────────
  'hashem_melech': 'ה׳ מלך',
  'psalm_030': 'מזמור שיר חנוכת הבית',
  'baruch_sheamar': 'ברוך שאמר',
  'hodu': 'פסוקי דזמרה',
  'mizmor_letodah': 'מזמור לתודה',
  'yehi_kevod': 'יהי כבוד',
  'ashrei': 'אשרי',
  'psalm_067': '',
  'psalm_121': '',
  'psalm_134': '',
  'psalm_146': '',
  'psalm_147': '',
  'psalm_148': '',
  'psalm_149': '',
  'psalm_150': '',
  'vayevarech_david': 'ויברך דוד',
  'az_yashir': 'שירת הים',
  'yishtabach': 'ישתבח',
  // ── Birkot Kriat Shema ────────────────────────────────────────────────────
  'yotzer_or': 'יוצר אור',
  'ahavah_rabbah': 'אהבה רבה',
  'emet_veyatziv': 'אמת ויציב',
  // ── Other morning segments ────────────────────────────────────────────────
  'beit_yaakov': 'בית יעקב',
  'tefila_ledavid_ps86': 'תפילה לדוד',
  'petihat_eliyahu': 'פתיחת אליהו',
  'korbanot_mincha': 'קרבנות',
  // ── Shacharit structure ────────────────────────────────────────────────────
  'barchu': 'ברכו',
  'shema': 'קריאת שמע',
  'ahavat_olam': 'אהבת עולם',
  'lamenatzeach': '',
  'ladavid': '',
  'yehi_shem': '',
  'yehi_chasdecha': '',
  // ── Amidah ─────────────────────────────────────────────────────────────────
  'amidah': 'תפילת עמידה',
  'amidah_intro': 'תפילת עמידה',
  'amidah_avot': 'אבות',
  'amidah_gevurot': 'גבורות',
  'amidah_kedushah_hashem': 'קדושת השם',
  'amidah_daat': 'דעת',
  'amidah_teshuva': 'תשובה',
  'amidah_selicha': 'סליחה',
  'amidah_geula': 'גאולה',
  'amidah_refuah': 'רפואה',
  'amidah_shanim': 'ברכת השנים',
  'amidah_galuyot': 'קבוץ גלויות',
  'amidah_mishpat': 'משפט',
  'amidah_minim': 'ברכת המינים',
  'amidah_tzaddikim': 'על הצדיקים',
  'amidah_yerushalayim': 'בנין ירושלים',
  'amidah_david': 'משיח בן דוד',
  'amidah_shema_koleinu': 'שומע תפילה',
  'amidah_retzeh': 'עבודה',
  'amidah_modim': 'הודאה',
  'amidah_shalom': 'שים שלום',
  'amidah_shalom_rav': 'שלום רב',
  'pitum_haketoreh_ashkenaz': '',
  'amidah_conclusion': 'אלקי נצור',
  'yehi_ratzon_pre_elokai': 'יהיו לרצון',
  // ── Chazarat HaShatz ───────────────────────────────────────────────────────
  'chazarat_hashatz_header': 'חזרת הש״ץ',
  'kedushah': 'קדושה',
  'kedushah_musaf': 'קדושה',
  'kedushah_ledorvador': 'לדור ודור',
  'modim_derabanan': 'מודים דרבנן',
  'birkat_kohanim': '',
  'birkat_kohanim_bracha': 'ברכת כהנים',
  'elokeinu_velohei_avoteinu': 'אלהינו ואלהי אבותינו',
  'anenu_shliach_tzibur': 'עננו',
  // ── Hallel + Lulav ────────────────────────────────────────────────────────
  'hallel': 'הלל',
  'hallel_half': 'הלל',
  'lulav_lshem_yichud': '',
  'lulav_bracha': 'ברכת הלולב',
  // ── Post-amidah ────────────────────────────────────────────────────────────
  'uva_letzion': 'ובא לציון',
  'uva_letzion_block': '',
  'uva_letzion_closing': '',
  'avinu_malkeinu': 'אבינו מלכנו',
  'aleinu': 'עלינו לשבח',
  'aleinu_al_ken': '',
  // ── Kaddish ────────────────────────────────────────────────────────────────
  'chatzi_kaddish_header': 'חצי קדיש',
  'kaddish_derabanan_header': 'קדיש דרבנן',
  'kaddish_yatom_header': 'קדיש יתום',
  'kaddish_titkabal_header': 'קדיש תתקבל',
  'kaddish_body': '',
  'kaddish_closing': '',
  'kaddish_derabanan_paragraph': '',
  'kaddish_titkabal_paragraph': '',
  // ── Sof hatfila ────────────────────────────────────────────────────────────
  'barchi_nafshi': 'ברכי נפשי',
  'ein_keloheinu': 'אין כאלהינו',
  'atah_hu_shehiktiruv': '',
  'pitum_haketoreh': 'פטום הקטורת',
  'tana_devei_eliyahu': '',
  'amar_rabbi_elazar': '',
  'shir_shel_yom_sunday': 'שיר של יום',
  'shir_shel_yom_monday': 'שיר של יום',
  'shir_shel_yom_tuesday': 'שיר של יום',
  'shir_shel_yom_wednesday': 'שיר של יום',
  'shir_shel_yom_thursday': 'שיר של יום',
  'shir_shel_yom_friday': 'שיר של יום',
  'shir_shel_yom_shabbat': 'שיר של יום',
  'shir_shel_yom_gra': 'שיר של יום',
  // EM extra mizmor additions after Shir Shel Yom (no separate header)
  'ssy_em_extra_chanukah': '',
  'ssy_em_extra_17_tammuz': '',
  'ssy_em_extra_esther_purim': '',
  'ssy_em_extra_tzom_gedalia_10_tevet': '',
  'ssy_em_extra_day_after_yk': '',
  'shir_hamaalot_lulei': '',
  'shofar_elul': '',
  // ── Maariv ─────────────────────────────────────────────────────────────────
  'maariv_aravim': 'מעריב ערבים',
  'maariv_ahavat_olam': 'אהבת עולם',
  'hashkivenu': 'השכיבנו',
  'emet_veemunh': 'אמת ואמונה',
  'yiru_einenu': 'יראו עינינו',
  'vehu_rachum': 'והוא רחום',
  'vehu_rachum_arvit': 'והוא רחום',
  'hashem_tzvaot_maariv': 'ה׳ צבאות עמנו',
  // ── Sefirat HaOmer ─────────────────────────────────────────────────────────
  'sefirat_haomer_header': 'ספירת העומר',
  'sefirat_haomer_lshem_yichud': 'לשם יחוד',
  'sefirat_haomer_lshem_yichud_long': 'לשם יחוד (נוסח ארוך)',
  'sefirat_haomer_birshut': '',
  'sefirat_haomer_bracha': '',
  'sefirat_haomer_day_count': '',
  'sefirat_haomer_harachaman': '',
  'sefirat_haomer_lamenatzeach': '',
  'sefirat_haomer_ana_bekoach': '',
  'sefirat_haomer_ribono_shel_olam': '',
  // ── EM mincha additions ────────────────────────────────────────────────────
  'mincha_em_lamenatzeach': 'למנצח',
  'mincha_em_hashem_malach': 'ה׳ מלך (ערב שבת)',
  'mincha_em_pesach': 'שיר — חול המועד פסח',
  'mincha_em_sukkot': 'שיר — חול המועד סוכות',
  'hallel_rc_psukim': 'ואברהם זקן',
  'psalm_042': 'למנצח משכיל לבני קרח',
  'psalm_107': 'הודו לה\'',
  // ── Kriat HaTorah ──────────────────────────────────────────────────────────
  'el_erech_apayim': 'אל ארך אפיים',
  'kriat_hatorah_shacharit': 'ברכות התורה',
  'kriat_hatorah_mincha': '',
  'kriat_hatorah_hotzaah': 'הוצאת ספר תורה',
  'kriat_hatorah_hachnasah': 'הכנסת ספר תורה',
  'hagbahah': 'הגבהה',
  'kriat_hatorah_reading_text': '',
  'kriah_rc': '',
  'kriah_chm_pesach_day_2': '',
  'kriah_chm_pesach_day_3': '',
  'kriah_chm_pesach_day_4': '',
  'kriah_chm_pesach_day_5': '',
  'kriah_chm_pesach_day_6': '',
  'kriah_chm_sukkot_day_2': '',
  'kriah_chm_sukkot_day_3': '',
  'kriah_chm_sukkot_day_4': '',
  'kriah_chm_sukkot_day_5': '',
  'kriah_chm_sukkot_day_6': '',
  'kriah_chm_sukkot_day_7': '',
  'kriah_chanukah_day_1': '',
  'kriah_chanukah_day_2': '',
  'kriah_chanukah_day_3': '',
  'kriah_chanukah_day_4': '',
  'kriah_chanukah_day_5': '',
  'kriah_chanukah_day_6': '',
  'kriah_chanukah_day_7': '',
  'kriah_chanukah_day_8': '',
  'kriah_purim': '',
  'kriah_rc_tevet': '',
  'kriah_fast_day': '',
  'haftarah_taanit': '',
  'haftarah_bracha_lifnei': 'ברכת ההפטרה',
  'haftarah_bracha_acharei_1': 'ברכות ההפטרה',
  'haftarah_bracha_acharei_2': '',
  'haftarah_bracha_acharei_3': '',
  'yehi_ratzon_mon_thu': '',
  // ── Musaf ──────────────────────────────────────────────────────────────────
  'musaf_header': 'מוסף',
  'amidah_musaf_retzeh': '',
  'amidah_musaf_intermediate_rc': 'ראש חודש',
  'amidah_musaf_intermediate_chm_pesach': 'חול המועד פסח',
  'amidah_musaf_intermediate_chm_sukkot': 'חול המועד סוכות',
  // ── Tachanun ───────────────────────────────────────────────────────────────
  'tachanun_header': 'תחנון',
  'tachanun': 'תחנון',
  'tachanun_nfilat_apayim': 'נפילת אפים',
  'tachanun_monday_thursday_addition': '',
  'tachanun_em_selichot_monday_thursday': '',
  'shomer_yisrael': 'שומר ישראל',
  'vidui_yud_gimel_midot': 'וידוי וי״ג מידות',
  // Canonical sub-segments of the vidui + 13-middot block (shared by tachanun & selichot)
  'vidui_intro': 'וידוי וי״ג מידות',
  'ashamnu': '',
  'sarnu': '',
  'el_erech_apayim_intro': '',
  'yud_gimel_midot': '',
  'vesalachta': '',
  'el_melech_yoshev': '',
  'el_melech_yoshev_em': '',
  'yud_gimel_midot_em': '',
  // ── Selichot (fast days + BaHaB) ─────────────────────────────────────────
  'selichot_gedalia': 'סליחות',
  'selichot_10_tevet': 'סליחות',
  'selichot_esther': 'סליחות',
  'selichot_17_tammuz': 'סליחות',
  'selichot_bahab': 'סליחות בה"ב',
  'selichot_bahab_sheni_kama': 'סליחות בה"ב',
  'selichot_bahab_chamishi': 'סליחות בה"ב',
  'selichot_bahab_sheni_batra': 'סליחות בה"ב',
  'hoshienu': 'הושיענו',
  'vihi_noam_before_psalm': '',
  'vihi_noam_after_psalm': '',
  'psukim_acharei_tanya': 'ה׳ צבאות עמנו',
  'al_tira': 'אל תירא',
  'seder_tzitzit_gadol': 'עטיפת טלית',
  'seder_tzitzit_gadol_em': 'עטיפת טלית',
  'ein_kohanim_bracha': '',
  'inline_toggle_tallit_gadol': '',
  'inline_toggle_shaliach_tzibbur': '',
  'inline_toggle_kohanim': '',
  // ── Birkat HaMazon ───────────────────────────────────────────────────────
  'inline_toggle_meal_type': '',
  'inline_toggle_zimmun': '',
  'inline_toggle_dining': '',
  'bhm_shir_hamaalot': '',
  'bhm_naharot': 'על נהרות בבל',
  'bhm_zimmun_open': 'זימון',
  'bhm_zimmun_sheva_intro': '',
  'bhm_zimmun_brit_intro': '',
  'bhm_zimmun_main_three': '',
  'bhm_zimmun_main_ten': '',
  'bhm_zimmun_main_sheva': '',
  'bhm_hazan_a': 'ברכת הזן',
  'bhm_hazan_kaamur': '',
  'bhm_hazan_chatima': '',
  'bhm_nodeh': 'ברכת הארץ',
  'bhm_al_hanisim_header': '',
  'bhm_al_hanisim_chanukah': '',
  'bhm_al_hanisim_purim': '',
  'bhm_veal_hakol': '',
  'bhm_rachem_open_ashk': 'בונה ירושלים',
  'bhm_rachem_open_sfard': 'בונה ירושלים',
  'bhm_rachem_body': '',
  'bhm_yaaleh_rc': '',
  'bhm_yaaleh_pesach': '',
  'bhm_yaaleh_sukkot': '',
  'bhm_rachem_chatima': '',
  'bhm_hatov': 'הטוב והמטיב',
  'bhm_harachaman_main': 'הרחמן',
  'bhm_dining_own_male': '',
  'bhm_dining_own_female': '',
  'bhm_dining_parents': '',
  'bhm_dining_guest': '',
  'bhm_dining_continuation': '',
  'bhm_guest_bracha': 'ברכת האורח',
  'bhm_bamarom': '',
  'bhm_brit_harachaman': '',
  'bhm_harachaman_rc': '',
  'bhm_harachaman_sukkot': '',
  'bhm_yezakenu_migdil': '',
  'bhm_yezakenu_migdol': '',
  'bhm_sheva_kos': 'שבע ברכות',
  'bhm_kos_bpg': 'ברכה על הכוס',

  // ── Birkat HaMazon — Edot HaMizrach ──────────────────────────────────────
  'bhm_em_lamnatzeach': '',
  'bhm_em_zimmun_open': 'זימון',
  'bhm_em_zimmun_main_three': '',
  'bhm_em_zimmun_main_ten': '',
  'bhm_em_hazan': 'ברכת הזן',
  'bhm_em_nodeh': 'ברכת הארץ',
  'bhm_em_al_hanisim_header': '',
  'bhm_em_al_hanisim_chanukah': '',
  'bhm_em_al_hanisim_purim': '',
  'bhm_em_al_hakol': '',
  'bhm_em_rachem': 'בונה ירושלים',
  'bhm_em_yaaleh_rc': '',
  'bhm_em_yaaleh_pesach': '',
  'bhm_em_yaaleh_sukkot': '',
  'bhm_em_rachem_chatima': '',
  'bhm_em_hatov': 'הטוב והמטיב',
  'bhm_em_harachaman_main': 'הרחמן',
  'bhm_em_harachaman_rc': '',
  'bhm_em_harachaman_sukkot': '',
  'bhm_em_harachaman_moadim': '',
  'bhm_em_harachaman_yita': '',
  'bhm_em_guest_bracha': 'ברכת האורח',
  'bhm_em_chatan': '',
  'bhm_em_mila': '',
  'bhm_em_yechayenu': '',
  'bhm_em_closing_migdil': '',
  'bhm_em_closing_migdol': '',
  'bhm_em_sheva_kos': 'שבע ברכות',

  // ── Berachah Me'ein Shalosh ──────────────────────────────────────────────
  // The whole blessing reads as one short flow under the screen title; no
  // visible per-segment headers are wanted.
  'inline_toggle_meein': '',
  'ms_opening': '',
  'ms_eretz': '',
  'ms_date_rc': '',
  'ms_date_chm_pesach': '',
  'ms_date_chm_sukkot': '',
  'ms_kiatah': '',
  'ms_chatima': '',

  // ── Tefilat HaDerech ─────────────────────────────────────────────────────
  'thd_main': '',
  // Post-blessing verses live in one optional accordion; the label is its header.
  'thd_additions': 'תוספות לתפילת הדרך',
  'thd_additions_em': 'תוספות לתפילת הדרך',

  // ── Purim ──────────────────────────────────────────────────────────────────
  'megillah_brachot_lifnei': 'ברכות קריאת המגילה',
  'megillah_brachot_lifnei_shnei': 'ברכות קריאת המגילה',
  'megillah_esther': 'מגילת אסתר',
  'megillah_bracha_acharei': '',
  'asher_henia': 'אשר הניא',
  'shoshanat_yaakov': 'שושנת יעקב',
  'arur_haman_em': 'ארור המן',

  // ── Hoshanot ───────────────────────────────────────────────────────────────
  'hoshanot_ashk_link': 'הושענות — לחץ להצגת הסבר',
  'hoshanot_day_2': 'הושענות',
  'hoshanot_day_3': 'הושענות',
  'hoshanot_day_4': 'הושענות',
  'hoshanot_day_5': 'הושענות',
  'hoshanot_day_6': 'הושענות',
  'hoshanot_hoshana_rabba': 'הושענות — הושענא רבא',

  // ── Selichot (collapsible omitted sections) ─────────────────────────────────
  'selichot_closing_omitted': 'קטעים מושמטים',
};
